create database assignments1;
use assignments1;
create table customer(customer_id int, first_name char(25), last_name char(25), email char(25), address char(50), city char(25), state char(25), zip int);
select * from customer;
insert into customer values(1,'Mahesh', 'jadhav', 'umesh@gmail.com', 'chandapur', 'Chincholi', 'gulbarga', 585305);
insert into customer values(2,'Ramesh', 'jadhav', 'Ramesh@gmail.com', 'chandapur', 'Chincholi', 'gulbarga', 585305);
insert into customer values(3,'Umesh', 'jadhav', 'umesh@gmail.com', 'chandapur', 'Chincholi', 'gulbarga', 585305);
insert into customer values(4,'Mukesh', 'jadhav', 'Ramesh@gmail.com', 'chandapur', 'Chincholi', 'gulbarga', 585305);
insert into customer values(5,'Srujan', 'jadhav', 'umesh@gmail.com', 'chandapur', 'Chincholi', 'gulbarga', 585305);
select * from customer;
select first_name, last_name from customer;
select first_name,city from customer where first_name like "M%" and city="Chincholi";
create table Orders(order_id int, order_date date, amount int, customer_id int);
insert into Orders values(101, '2020-12-01', 100, 1);
insert into Orders values(102, '2020-11-01', 200, 2);
insert into Orders values(103, '2020-10-01', 300, 3);
insert into Orders values(104, '2020-09-01', 400, 4);
insert into Orders values(105, '2020-08-01', 500, 5);
select * from Orders;
update Orders set amount = 100 where customer_id=3;
select min(amount) from Orders;
select max(amount) from Orders;
select avg(amount) from Orders;
select * from Orders order by amount DESC;